# Generated by Django 6.1 on 2026-09-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='machinery',
            options={'verbose_name_plural': 'Machinery'},
        ),
    ]
